name: 'PR Title Emoji Stripper'
description: 'Removes emoji characters from PR titles.'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node12'
  main: 'dist/index.js'
